name: 08 - Using Variables

on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: 'I am a workflow env var'
  OVERWRITTEN: 'I will be overwritten'
  UNDEFINED_VAR_WITH_DEFAULT: ${{vars.UNDEFINED_VAR || 'default value' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am a job env var'
      OVERWRITTEN: 'I have been overwritten at the job level'
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: 'I am a step env var'
          step_var2: 'I am another step env var'
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step env var 2: $step_var2"
          echo "Job env var: ${{ env.JOB_VAR }}"
          echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
          echo "Overwritten: ${{ env.OVERWRITTEN }}"
      - name: Overwrite job variable
        env:
          OVERWRITTEN: 'I have been overwritten at the step level'
        run: |
          echo "Step env var: ${{ env.OVERWRITTEN }}"
  echo_2:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: |
          echo "Org var: ${{ vars.ORG_VAR }}"
          echo "Org overwritten var: ${{ vars.OVERWRITTEN_VAR}}"
          echo "REPO var: ${{vars.REPOSITORY_VAR}}"
  echo_prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: PRINT PROD VARIABLES
        run: |
          echo "Org var: ${{ vars.ORG_VAR }}"
          echo "Org overwritten var: ${{ vars.OVERWRITTEN_VAR}}"
          echo "REPO var: ${{vars.REPOSITORY_VAR}}"
          echo "Environmet var: ${{vars.TARGET_VAR}}"
  echo_undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print undefined variables
        run: |
          echo "Org var: ${{env.UNDEFINED_VAR_WITH_DEFAULT}}"
