# See 17-custom-actions/README.md for more information
# about how to create and use custom actions in workflows.

name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options:
          - 'https://www.bbc.co.uk'
          - 'https://www.invalid-dkjdkslfjlsda.com'
          - 'https://example-test.com'
      max_trials: 
        default: '10'
        required: false  
      delay:
        default: '5'
        required: false


jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL 
        id: update-deps
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url}}
          max_trials: ${{inputs.max_trials}}
          delay: ${{inputs.delay}}