name: 19 - 2 - Managing concurrency

on: 
    workflow_dispatch

jobs:
    ping-url:
        runs-on: ubuntu-latest
        concurrency:
            group: $$ {{ github.workflow }}-${{ github.ref }}
        steps:
        - uses: actions/checkout@v4
        - name: Ping URL 
          id: ping-url
          uses: ./.github/actions/docker-ping-url
          with:
            url: https://www.invalid-ubfadufhbaudhfua.com
            max_trials: 20
            delay: 5
    ping-url-without-concurrency:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Ping URL 
          id: ping-url
          uses: ./.github/actions/docker-ping-url
          with:
            url: https://www.invalid-ubfadufhbaudhfua.com
            max_trials: 20
            delay: 5